services:
  postgres:
    image: postgres:10
    volumes:
      - ./storage/postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      PGDATA: "/var/lib/postgresql/data"
    restart: always

  redmine:
    build:
      context: .
    image: redmine:latest
    ports:
      - "80:3000"
    volumes:
      - ./storage/docker_redmine-plugins:/usr/src/redmine/plugins
      - ./storage/docker_redmine-themes:/usr/src/redmine/public/themes
      - ./storage/docker_redmine-data:/usr/src/redmine/files
    env_file:
      - .env
    restart: always

