db_password: "{{ vault_postgres_password }}"
db_user: "{{ vault_postgres_user }}"
db_name: "{{ vault_postgres_db }}"
db_host: "{{ vault_db_host }}"
db_port: "{{ vault_db_port }}"

docker_install_compose: true
docker_compose_version: "2.20.0"
docker_users:
  - "{{ ansible_user }}"

docker_system_packages:
  - docker.io
  - docker-compose-plugin

pip_install_packages: []

# Datadog HTTP Check URI
datadog_http_check_url: "http://{{ ansible_host }}:{{ redmine_port | default(80) }}/"

