$ANSIBLE_VAULT;1.1;AES256
63343433613736356434616338343965303737353231646161633732393338306361353261323033
6134353330343737636531343631333733633330666561660a373066306466353738373138313234
65336630636234616630343936666132313331376665316435363535373839373539306234633462
6632313437623162340a653435623863643461356132636462333630343136363864616136636638
32373434633235613265343931383537306431393664343737366562643233666533333732643665
61353833383233356333386536393931306436623962343337356634623339353737626636343437
65663335346436363630616635643365623537376664313832356662663238353437666330366436
62336162636536376131303466353363343563316131643161356238306337353663303736313034
65653435343932303765336363346334306435333861333835613839633666346139353834313734
36636235643666383238633862333061313461306362333835316239393236383235336535616264
64373830346137326239656331323738643765346564623835386639306532666532313064326361
31336336383135613861306534666337346265316233316430653934633232363564343132376562
36336434663562653063656536663962626638383636643031393163343163626334
